name: Build, Publish Docker image to ECR
on:
  workflow_dispatch:
    inputs:
      ecrrepo:
        description: "Name of the ECR Repository"
        type: string
        default: github-gists-api
        required: false
jobs:
    build_docker_image:
        name: build_docker_image
        runs-on: ubuntu-latest

        permissions:
          id-token: write
          contents: read
        
        steps:
          - name: Checkout Repo
            uses: actions/checkout@v5
            with:
                ref: main
        
          - name: Assume IAM Role
            uses: aws-actions/configure-aws-credentials@v5.1.0
            with:
              role-to-assume: ${{ secrets.IAM_ROLE_TO_ASSUME }}
              role-session-name: ecr-image-push
              aws-region: us-west-2
    
          - name: Login to Amazon ECR
            id: login-ecr
            uses: aws-actions/amazon-ecr-login@v2
          
          - name: Build Docker Image & Publish to ECR
            env:
              ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
              ECR_REPOSITORY: github-gists-api
              IMAGE_TAG: '1.0.0'
            run: |
              docker build $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
              docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG


  